name: Test

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    name: R
    steps:
      - uses: actions/checkout@v3
      - name: Sys deps
        run: |
          DEBIAN_FRONTEND="noninteractive" apt-get update -y
          DEBIAN_FRONTEND="noninteractive" apt-get install -y sudo software-properties-common dialog apt-utils tzdata libpng-dev locales
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
      - run: Rscript -e 'print("hello")'
