name: Test

on:
  push:
    branches:
      - master
      - main
      - manually

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    name: R
    steps:
      - uses: actions/checkout@v3
      - name: Sys deps
        run: |
          DEBIAN_FRONTEND="noninteractive" apt-get update -y
          DEBIAN_FRONTEND="noninteractive" apt-get install -y sudo software-properties-common dialog apt-utils tzdata libpng-dev locales curl
      - name: Setup R
        run: |
          `which sudo` curl -L https://rig.r-pkg.org/deb/rig.gpg -o /etc/apt/trusted.gpg.d/rig.gpg
          `which sudo` sh -c 'echo "deb http://rig.r-pkg.org/deb rig main" > /etc/apt/sources.list.d/rig.list'
          `which sudo` apt update
          `which sudo` apt install r-rig
          rig add release
      - run: Rscript -e 'print("hello")'
